### ISSUE TITLE
Implement Color Literal Syntax Highlighting

### ISSUE THREAD

**Issue by XojoGermany** [jimmckay/XojoSyntaxTM#2]
I just found out by accident that Github uses this repository for syntax highlighting of Xojo code. Currently, color literals are not yet displayed in color as we are used to in the Xojo IDE. It would be nice if this can be added to the engine so that Github Markdown for (inline) code also renders something like the Xojo IDE code editor: `&c000000`.

**Comment by jimmckay** [comment]
I did try to find a way to do this previously, but GitHub uses the textmate grammars only to detect the parts of language, not to colorize them. That happens elsewhere. So this would likely require talking github into adding it to their main themes.
